services:
  haproxy-acme:
    image: flobernd/haproxy-acme:latest
    container_name: haproxy-acme
    restart: unless-stopped
    environment:
      - "ACME_DEBUG=0"
      - "ACME_UPGRADE=1"
      - "ACME_CRON=1"
    volumes:
      - ./volume/acme:/var/lib/acme:rw
