services:
  haproxy-acme:
    image: flobernd/haproxy-acme-http01:latest
    container_name: haproxy-acme-http01
    restart: unless-stopped
    environment:
      - "HAPROXY_HTTP_PORT=80"
      - "HAPROXY_HTTPS_PORT=443"
      - "ACME_DEBUG=0"
      - "ACME_UPGRADE=1"
      - "ACME_CRON=1"
      - "ACME_MAIL=mail@domain.com"
      - "ACME_SERVER=letsencrypt_test"
      - "ACME_DOMAIN=domain.com"
      - "ACME_KEYLENGTH=ec-256"
      - "SERVER_ADDRESS=whoami"
      - "SERVER_PORT=80"
      - "SERVER_DIRECTIVES="
    volumes:
      - ./volume/acme:/var/lib/acme:rw
    ports:
      - 80:80
      - 443:443
    sysctls:
      - net.ipv4.ip_unprivileged_port_start = 0

  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped
